src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Create_Revenue_Projections__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Setting this field to true creates Billing Plans automatically and qualifies the Opportunity for Revenue Projections.</description>
        <inlineHelpText>Setting this field to true creates Billing Plans automatically and qualifies the Opportunity for Revenue Projections.</inlineHelpText>
        <label>Create Revenue Projections</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

objects/Opportunity_Billing_Plan__c.object
<CustomObject>
    <description>Opportunity Billing Plan based on time to full contract and billing method.</description>
    <fields>
        <fullName>Billing_Date__c</fullName>
        <label>Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Rate__c</fullName>
        <label>Billing Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Billing Plans</relationshipLabel>
        <relationshipName>Opportunity_Billing_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Billing Plan</label>
    <nameField>
        <label>Opportunity Billing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Billing Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Revenue_Projection_Batch_Processed__c</fullName>
        <description>Specifies whether the revenue projection batch has processed this record</description>
        <inlineHelpText>Specifies whether the revenue projection batch has processed this record</inlineHelpText>
        <label>Revenue Projection Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Revenue_Projection_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Revenue_Projections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mode__c</fullName>
        <label>Mode</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Code</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Revenue_Projections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Revenue_Projections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Revenue Projection (Opportunity)</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Projections (Opportunity)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/rp_opportunityRevenueProjectionJob.cls
//Author: Rajeev Shekhar
public class rp_opportunityRevenueProjectionJob implements Queueable {
    
    List<String> opportunityIds;
    
    public rp_opportunityRevenueProjectionJob(List<String> opportunityIds) {
        this.opportunityIds = opportunityIds;    
    }
    
    public void execute(QueueableContext context) {
        if(!opportunityIds.isEmpty()) { 
            Set<Id> oppIds = new Set<Id>();
            Set<Id> productIds = new Set<Id>();
            Map<Id,List<Opportunity_Billing_Plan__c>> obpsmap = new Map<Id,List<Opportunity_Billing_Plan__c>>();
            Revenue_Projection_Opportunity__c[] rpolist = new List<Revenue_Projection_Opportunity__c>();
            List<OpportunityLineItem> oliToUpdate = new List<OpportunityLineItem>();      

            OpportunityLineItem[] scope = [SELECT Id, Opportunity.Name, OpportunityId, Opportunity.AccountId, TotalPrice, Revenue_Projection_Batch_Processed__c,
                                           Opportunity.Create_Revenue_Projections__c, Product2Id, Opportunity.CurrencyISOCode FROM OpportunityLineItem WHERE
                                           OpportunityId IN :opportunityIds AND Opportunity.Create_Revenue_Projections__c = true AND Revenue_Projection_Batch_Processed__c = 'Pending'];
            
            for(OpportunityLineItem oli : scope) {
                oppIds.add(oli.OpportunityId);
                productIds.add(oli.Product2Id);
            }
            
            for(Opportunity_Billing_Plan__c obp : [SELECT Id, Billing_Date__c, Billing_Rate__c, Opportunity__c, Order__c FROM Opportunity_Billing_Plan__c WHERE Opportunity__c In :oppIds]) {
                if(obpsmap.containsKey(obp.Opportunity__c)) {
                    obpsmap.get(obp.Opportunity__c).add(obp);
                } else {
                    obpsmap.put(obp.Opportunity__c,new List<Opportunity_Billing_Plan__c>{obp});
                }
            }
            
            Revenue_Projection_Opportunity__c[] rpdelete = rp_opportunityRevenueProjectionFunctions.getOpportunityProjectionsToDelete(obpsmap.keySet(),productIds);
             
            for(OpportunityLineItem oli : scope) {
                if(obpsmap.containsKey(oli.OpportunityId) && obpsmap.get(oli.OpportunityId) != null) {
                    for(Opportunity_Billing_Plan__c obp : obpsmap.get(oli.OpportunityId)) {
                        Revenue_Projection_Opportunity__c rpo = new Revenue_Projection_Opportunity__c();
                        rpo.Opportunity__c = oli.OpportunityId;
                        rpo.Date__c = obp.Billing_Date__c;
                        if(oli.TotalPrice != null) rpo.Amount__c = ((obp.Billing_Rate__c) * (oli.TotalPrice) / 100);
                        rpo.Account__c = oli.Opportunity.AccountId;
                        rpo.Mode__c = 'Code';
                        rpo.Product__c = oli.Product2Id;
                        rpo.Status__c = 'Valid';
                        rpo.Name = oli.Opportunity.Name;
                        rpo.CurrencyISOCode = oli.Opportunity.CurrencyISOCode;
                        rpolist.add(rpo);
                    }
                    oliToUpdate.add(oli);
                }        
            }
            
            if(rpolist.size() > 0) {
                try{
                    insert rpolist;
                    if(rpdelete.size() >0) delete rpdelete;
                    for(OpportunityLineItem o : oliToUpdate) {
                        o.Revenue_Projection_Batch_Processed__c = 'Processed';
                    }
                    update oliToUpdate;
                } Catch(Exception e) {
                    System.debug('Exception: '+e);    
                }
            }
        }          
    }
}