src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Billing_Method__c</fullName>
        <inlineHelpText>Values counted in months (e.g. quarterly equals 3 months)</inlineHelpText>
        <label>Invoicing Interval</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly-1</fullName>
                    <default>true</default>
                    <label>Monthly</label>
                </value>
                <value>
                    <fullName>Quarterly-3</fullName>
                    <label>Quarterly</label>
                </value>
                <value>
                    <fullName>HalfYearly-6</fullName>
                    <label>Half Yearly</label>
                </value>
                <value>
                    <fullName>Annually-12</fullName>
                    <label>Annually</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Create_Revenue_Projections__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Setting this field to true creates Billing Plans automatically and qualifies the Opportunity for Revenue Projections.</description>
        <inlineHelpText>Setting this field to true creates Billing Plans automatically and qualifies the Opportunity for Revenue Projections.</inlineHelpText>
        <label>Create Revenue Projections</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_Deal_Duration_months__c</fullName>
        <inlineHelpText>Choose the number of months that you expect the potential Contract to be valid for. 
If you expect an &apos;Evergreen&apos; Contract, select &apos;Evergreen&apos;. 
You may estimate in the beginning of the process, but an accurate duration must be entered by stage &apos;won&apos;.</inlineHelpText>
        <label>Contract Duration (months)</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Time_to_full_Contract_implementation__c</fullName>
        <defaultValue>12</defaultValue>
        <inlineHelpText>Please enter the data in terms of months.</inlineHelpText>
        <label>Time to full Contract implementation</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time_to_revenue_days__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Please enter the expected number of days between the Opportunity Close Date and when the revenue starts.</inlineHelpText>
        <label>Time to first invoice (days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

objects/Opportunity_Billing_Plan__c.object
<CustomObject>
    <description>Opportunity Billing Plan based on time to full contract and billing method.</description>
    <fields>
        <fullName>Billing_Date__c</fullName>
        <label>Billing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Billing_Rate__c</fullName>
        <label>Billing Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Billing Plans</relationshipLabel>
        <relationshipName>Opportunity_Billing_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Opportunity Billing Plan</label>
    <nameField>
        <label>Opportunity Billing Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Billing Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Revenue_Projection_Batch_Processed__c</fullName>
        <description>Specifies whether the revenue projection batch has processed this record</description>
        <inlineHelpText>Specifies whether the revenue projection batch has processed this record</inlineHelpText>
        <label>Revenue Projection Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Processed</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                    <default>true</default>
                    <label>Pending</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

src/objects/Revenue_Projection_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Revenue_Projections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Revenue_Projections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Revenue Projection (Opportunity)</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Projections (Opportunity)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/rp_oppBillingPlans.cls
//Author: Rajeev S

public with sharing class rp_oppBillingPlans {
    
    //Create the Opportunity Billing Plan data
    public static void actionsOnInsert(List<Opportunity> opps) {
        createBillingPlans(opps);
    }
    
    //Recreate the Opportunity Billing Plan data
    public static void actionsOnUpdate(List<Opportunity> opps,Map<Id,Opportunity> oldMap) {
        Set<String> oppIds = new Set<String>();
        Set<String> oppIdsUpdate = new Set<String>();
        
        for(Opportunity o : opps) {
            if(o.Create_Revenue_Projections__c) {
                Opportunity oldOpp = oldMap.get(o.Id);
                if((o.Create_Revenue_Projections__c) && (oldOpp.Create_Revenue_Projections__c == false))
                    oppIds.add(o.Id);
                if((o.Billing_Method__c != null) && (o.Billing_Method__c != oldOpp.Billing_Method__c))
                    oppIds.add(o.Id);
                if((o.Time_to_full_Contract_implementation__c != null) && (o.Time_to_full_Contract_implementation__c != oldOpp.Time_to_full_Contract_implementation__c))
                    oppIds.add(o.Id);
                if((o.Potential_Deal_Duration_months__c != null) && (o.Potential_Deal_Duration_months__c != oldOpp.Potential_Deal_Duration_months__c))
                    oppIds.add(o.Id);    
                if((o.Time_to_revenue_days__c != null) && (o.Time_to_revenue_days__c != oldOpp.Time_to_revenue_days__c))
                    oppIdsUpdate.add(o.Id);
                if((o.CloseDate != null) && (o.CloseDate != oldOpp.CloseDate))
                    oppIdsUpdate.add(o.Id);        
            }            
        }
        
        if(oppIds.size() >0) {
            deleteBillingPlans(oppIds);
            invalidateRevenueProjections(oppIds);
            createBillingPlans(opps);
            updateOpportunityLineItems(oppIds);
        }
        
        if(oppIdsUpdate.size() >0 && oppIds.size() == 0) {
            updateBillingPlans(oppIdsUpdate,oldMap);
        }    
    }
    
    //Create Billing Plan record when Opportunities are inserted
    private static void createBillingPlans(List<Opportunity> opps) {
        Boolean allowRun = rp_checkRecursive.billingPlanCodeCheckInsert();
        List<String> opportunityIds = new List<String>();
        if(allowRun) {
            Map<String,Schema.RecordTypeInfo> oppRT = Opportunity.sObjectType.getDescribe().getRecordTypeInfosByDeveloperName();
            String contractRT_Id = oppRT.get('Deal').getRecordTypeId();
            String spotRT_Id = oppRT.get('Spot').getRecordTypeId();
            List<Opportunity_Billing_Plan__c> billingPlans = new List<Opportunity_Billing_Plan__c>();
            Map<String,Integer> billingMethodMap = new Map<String,Integer>();
            for(Schema.PicklistEntry F : Opportunity.Billing_Method__c.getDescribe().getPicklistValues()) {
                billingMethodMap.put(F.getValue(),Integer.valueOf(F.getValue().substringAfter('-')));
            }
            for(Opportunity o : opps) {
                if(o.RecordTypeId == contractRT_Id && o.StageName == 'Preparing Proposal' && o.Create_Revenue_Projections__c) {
                    if(String.IsNotBlank(o.Billing_Method__c) && o.Time_to_full_Contract_implementation__c != null) {
                        opportunityIds.add(o.Id);
                        Integer potentialDealDuration = null;
                        if(o.Potential_Deal_Duration_months__c != null) potentialDealDuration = Integer.valueOf(o.Potential_Deal_Duration_months__c);
                        Integer totalDuration = (o.Time_to_full_Contract_implementation__c + potentialDealDuration).intValue();
                        Integer billingMethodValue = billingMethodMap.get(o.Billing_Method__c);
                        Decimal iterations = null;
                        if(billingMethodValue != null) iterations = Math.floor(o.Time_to_full_Contract_implementation__c / billingMethodValue);
                        Date billingDate = null;
                        Integer order = 0;
                        for(integer i=1;i<=iterations.intValue();i++) {
                            Opportunity_Billing_Plan__c obp = new Opportunity_Billing_Plan__c();
                            obp.Opportunity__c = o.Id;
                            obp.Name = o.Name;
                            obp.Order__c = i;
                            if(i == 1) billingDate = o.CloseDate.addDays(o.Time_to_revenue_days__c.intValue());
                            if(i > 1) billingDate = billingDate.addMonths(billingMethodValue);
                            obp.Billing_Date__c = billingDate;
                            obp.Billing_Rate__c = (100 / iterations) * i;
                            order++;                         
                            billingPlans.add(obp);
                        }
                        if(billingDate != null) billingDate = billingDate.addMonths(billingMethodValue);
                        order++;
                        for(integer i=1;i<=((totalDuration/billingMethodValue)-iterations-iterations);i++) {
                            Opportunity_Billing_Plan__c obp = new Opportunity_Billing_Plan__c();
                            obp.Opportunity__c = o.Id;
                            obp.Name = o.Name;
                            obp.Order__c = order;
                            if(i > 1) billingDate = billingDate.addMonths(billingMethodValue);
                            obp.Billing_Date__c = billingDate;
                            obp.Billing_Rate__c = 100;
                            order++;                         
                            billingPlans.add(obp);
                        }
                        if(billingDate != null) billingDate = billingDate.addMonths(billingMethodValue);
                        for(integer i=1;i<iterations.intValue();i++) {
                            Opportunity_Billing_Plan__c obp = new Opportunity_Billing_Plan__c();
                            obp.Opportunity__c = o.Id;
                            obp.Name = o.Name;
                            obp.Order__c = order;
                            if(i > 1) billingDate = billingDate.addMonths(billingMethodValue);
                            obp.Billing_Date__c = billingDate;
                            obp.Billing_Rate__c = 100 - ((100 / iterations) * i);
                            order++;                         
                            billingPlans.add(obp);
                        }
                    }
                } else if(o.RecordTypeId == spotRT_Id && o.StageName == 'Preparing Proposal' && o.Create_Revenue_Projections__c) {
                    opportunityIds.add(o.Id);
                    Opportunity_Billing_Plan__c obpSpot = new Opportunity_Billing_Plan__c(Name = o.Name,Order__c = 1,
                        Billing_Rate__c = 100, Billing_Date__c = o.CloseDate.addDays(o.Time_to_revenue_days__c.intValue()),Opportunity__c = o.Id);
                        insert obpSpot;
                }   
            }
            if(billingPlans.size() >0) insert billingPlans;
            if(opportunityIds.size() >0) System.enqueueJob(new rp_opportunityRevenueProjectionJob(opportunityIds)); //submit job
        }        
    }
    
    //Update Opportunity Billing Plans when certain fields change on Opportunity
    private static void updateBillingPlans(Set<String> oppIds,Map<Id,Opportunity> oldMap) {
        Opportunity_Billing_Plan__c[] obps = [SELECT Id, Billing_Date__c, Order__c, Opportunity__r.CloseDate,Opportunity__r.Time_to_revenue_days__c FROM Opportunity_Billing_Plan__c
                                              WHERE Opportunity__c IN :oppIds Order By Opportunity__c,Order__c ASC];
        for(Opportunity_Billing_Plan__c o : obps) {
            Decimal ttrdiff = o.Opportunity__r.Time_to_revenue_days__c - oldmap.get(o.Opportunity__c).Time_to_revenue_days__c; 
            Integer datedifference = oldmap.get(o.Opportunity__c).CloseDate.daysBetween(o.Opportunity__r.CloseDate);
            o.Billing_Date__c = o.Billing_Date__c.addDays(datedifference + ttrdiff.intValue()); 
        }
        update obps;                                      
    }
    
    //Delete the Opportunity Billing Plan data
    private static void deleteBillingPlans(Set<String> oppIds) {
        Opportunity_Billing_Plan__c[] obp = [SELECT Id FROM Opportunity_Billing_Plan__c WHERE Opportunity__c IN :oppIds];
        delete obp;
    }
    
    //Invalidate the Opportunity Revenue Projection data
    public static void invalidateRevenueProjections(Set<String> oppIds) {
        Revenue_Projection_Opportunity__c[] rpo = [SELECT Id,Status__c FROM Revenue_Projection_Opportunity__c WHERE Opportunity__c IN :oppIds];
        List<Revenue_Projection_Opportunity__c> updateRpo = new List<Revenue_Projection_Opportunity__c>();
        for(Revenue_Projection_Opportunity__c r : rpo) {
            if(r.Status__c != 'Invalid') {
                r.Status__c = 'Invalid';
                updateRpo.add(r);
            }
        }
        if(updateRpo.size() >0) update updateRpo;
    }
    
    //Invalidate the Opportunity Revenue Projection data based on Products
    public static void invalidateRevenueProjectionsByProducts(Set<String> oppIds, Set<String> prodIds) {
        Revenue_Projection_Opportunity__c[] rpo = [SELECT Id,Status__c FROM Revenue_Projection_Opportunity__c WHERE Opportunity__c IN :oppIds
                                                   AND Product__c IN :prodIds];
        List<Revenue_Projection_Opportunity__c> updateRpo = new List<Revenue_Projection_Opportunity__c>();
        for(Revenue_Projection_Opportunity__c r : rpo) {
            if(r.Status__c != 'Invalid') {
                r.Status__c = 'Invalid';
                updateRpo.add(r);
            }
        }
        if(updateRpo.size() >0) update updateRpo;
    }
    
    //Update the Opportunity Products
    public static void updateOpportunityLineItems(Set<String> oppIds) {
        List<OpportunityLineItem> lineItems = new List<OpportunityLineItem>();
        for(OpportunityLineItem o : [SELECT Id, Revenue_Projection_Batch_Processed__c FROM OpportunityLineItem WHERE OpportunityId IN :oppIds]) {
            if(o.Revenue_Projection_Batch_Processed__c != 'Pending') {
                o.Revenue_Projection_Batch_Processed__c = 'Pending';
                lineItems.add(o);
            }
        }
        if(lineItems.size() > 0) update lineItems;
    }    
}