src/objects/Revenue_Projection_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Revenue_Projections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Revenue_Projections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Revenue Projection (Opportunity)</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Projections (Opportunity)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/rp_opportunityRevenueProjectionFunctions.cls
//Author: Rajeev Shekhar

public inherited sharing class rp_opportunityRevenueProjectionFunctions {

    public static List<Revenue_Projection_Opportunity__c> getOpportunityProjectionsToDelete(Set<Id> oppIds, Set<Id> productIds) {
        Revenue_Projection_Opportunity__c[] rpdelete = [SELECT Id FROM Revenue_Projection_Opportunity__c WHERE Opportunity__c IN :oppIds
                                                        AND Product__c IN :productIds AND Status__c = 'Invalid'];
       return rpdelete;                                                
    }

}